### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Petrkiller2** [ras0k/auto-lyrics#1]
I'd like to reccomend a feature that lets the user select between downloading a youtube video OR using a file that is in the colab's drive OR upload it if not included.

**Comment by ras0k** [comment]
I agree that would be useful, when I wanna use a custom file I usually revert to v5

**Comment by ras0k** [comment]
I'll try to make it happen this week, thank you for the suggestion!

**Comment by ras0k** [comment]
Done.

Let me know if you find any bugs or have other ideas 😊
